// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkkcbmphcbqcmcdapvac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indra2NibXBoY2JxY21jZGFwdmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODQ5MjgsImV4cCI6MjA1NjQ2MDkyOH0.W0p1X2qJ17uJOeEr4IJgk2cTCkhxw0OICyhBjMevfGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);